const html = require("eslint-plugin-html");

module.exports = [
  {
    files: ["**/*.html"],
    plugins: { html },
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        CustomEvent: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        DragEvent: "readonly",
        Node: "readonly",
        Element: "readonly",
        location: "readonly",
        history: "readonly",
        navigator: "readonly",
        alert: "readonly",
        confirm: "readonly",
        fetch: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        Object: "readonly",
        Array: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        RegExp: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        Error: "readonly",
        isNaN: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
      },
    },
    rules: {
      "no-undef": "warn",
      "no-unused-vars": "off", // HTML onclick handlers escape detection
      "no-duplicate-case": "error",
      "no-const-assign": "error",
      "no-extra-semi": "warn",
      "no-irregular-whitespace": "warn",
      "no-unreachable": "warn",
      "no-unsafe-negation": "error",
      "no-sparse-arrays": "warn",
      "valid-typeof": "error",
      "no-cond-assign": "warn",
      "no-constant-condition": "warn",
      "no-debugger": "warn",
      "no-empty": "warn",
      "no-extra-boolean-cast": "warn",
      "no-redeclare": "warn",
      "no-unsafe-optional-chaining": "error",
    },
  },
];
